%% lwEnumDefinition.m - Enumeration definitions
% Define the required Enums for codegen structure

% Author: wsh.
% Email: wsh_buaa@buaa.edu.cn

%Constant value
RAD2DEG = single(57.2957795);
DEG2RAD = single(0.0174533);
CONSTANTS_ONE_G = 9.80665; % m/s^2
CONSTANTS_RADIUS_OF_EARTH = 6371000; % meters (m)
MAX_MISSION_ITEM = 15; % 太多消耗系统内存，可能会出问题。PX4最多支持42个

Simulink.defineIntEnumType('VehicleType',{...
    'LIFTING_WING',...
    'MULTICOPTER',...
    'FIXED_WING'},...
    [0;1;2]);
Simulink.defineIntEnumType('FlightMode',{...
    'PILOT',...
    'AUTO',...
    'OFFBOARD'},...
    [0;1;2]);
Simulink.defineIntEnumType('ControlMode',{...
    'ARM',...
    'DISARM',...
    'MANUAL',...
    'ACRO',...
    'STABILIZED',...
    'ALTITUDE',...
    'POSITION',...
    'RTL',...
    'LANDING',...
    'LOITER',...
    'MISSION'},...
    [0;1;2;3;4;5;6;7;8;9;10]);
